chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns =[
	path('api/create_room/<str:uuid>', views.create_room, name="create_room"),
	path('chat-admin/', views.admin, name='admin'),
	path('chat-logout/', views.logout_user, name='logout'),
	path('chat-admin/add-user/', views.add_user, name='add_user'),
	path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user_detail'),
	path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit_user'),
	path('chat-admin/<str:uuid>/', views.room, name='room'),
	path('chat-admin/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

jatte/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

account/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone


class CustomUserManager(UserManager):
    def _create_user(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")
        
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)
    
    def create_superuser(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(name, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    AGENT = 'agent'
    MANAGER = 'manager'

    ROLES_CHOICES = (
        (AGENT, 'Agent'),
        (MANAGER, 'Manager'),
    )
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLES_CHOICES, default=AGENT)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

chat/models.py
from django.db import models

# Create your models here.


from account.models import User

class Message(models.Model):
	body = models.TextField()
	sent_by = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	created_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

	class Meta:
		ordering = ('created_at', )

	def __str__(self):
		return self.sent_by



class Room(models.Model):

	WAITING = 'waiting'
	ACTIVE = 'active'
	CLOSED = 'closed'

	CHOICES_STATUS = (
		(WAITING, 'Waiting'),
		(ACTIVE, 'Active'),
		(CLOSED, 'Closed')
	)

	uuid = models.CharField(max_length=255)
	client = models.CharField(max_length=255)
	agent = models.ForeignKey(User, related_name="rooms", blank=True, null=True, on_delete=models.SET_NULL)
	messages = models.ManyToManyField(Message, blank=True)
	url = models.CharField(max_length=255, blank=True, null=True)
	status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=WAITING)
	created_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-created_at',)

	def __str__(self):
		return f'{self.client} - {self.uuid}'

chat/views.py
from django.shortcuts import render, redirect
import json
from django.http import JsonResponse
from django.contrib.auth.models import Group, User
from django.views.decorators.http import require_POST
from .models import Room
from django.contrib.auth.decorators import login_required
from account.models import User
from account.forms import AddUserForm, EditUserForm
from django.contrib import messages
from django.contrib.auth import logout


# Create your views here.

@require_POST
def create_room(request, uuid):
	name = request.POST.get('name', '')
	url = request.POST.get('url', '')

	Room.objects.create(uuid=uuid, client=name, url=url)

	return JsonResponse({'message':'room created'})



@login_required
def admin(request):

	rooms = Room.objects.all()
	users = User.objects.filter(is_staff=True)

	context = {
		'rooms':rooms,
		'users':users
	}
	return render(request, 'chat/admin.html', context)



@login_required
def room(request, uuid):

	room = Room.objects.get(uuid=uuid)

	if room.status == room.WAITING:
		room.status = room.ACTIVE
		room.agent = request.user
		room.save()

	return render(request, 'chat/room.html', {'room':room})


@login_required
def delete_room(request, uuid):

	if request.user.has_perm('room.delete_room'):
		room = Room.objects.get(uuid=uuid)
		room.delete()
		messages.info(request, 'The Room Was Deleted!')

		return redirect('/chat-admin/')
	else:

		messages.error(request, 'You dont\'t access to delete users!')

		return redirect('/chat-admin/')


@login_required
def user_detail(request, uuid):
	user = User.objects.get(pk=uuid)
	rooms = user.rooms.all()


	return render(request, 'chat/user_detail.html', {'user':user, 'rooms':rooms})


@login_required
def edit_user(request, uuid):

	if request.user.has_perm('user.add_user'):
		user = User.objects.get(pk=uuid)

		if request.method == 'POST':
			form = EditUserForm(request.POST, instance=user)

			if form.is_valid():
				form.save()
				messages.success(request, 'The Changes Was Saved!')

				return redirect('/chat-admin/')
		else:	
			form = EditUserForm(instance=user)

			return render(request, 'chat/edit_user.html', {'user':user, 'form':form})
	else:
		messages.error(request, 'You dont\'t access to edit users!')

		return redirect('/chat-admin/')

@login_required
def logout_user(request):
	logout(request)
	messages.success(request, 'You have been logout Successfully!')
	return redirect('/chat-admin/')

@login_required
def add_user(request):
	
	if request.user.has_perm('user.add_user'):

		if request.method == 'POST':

			form = AddUserForm(request.POST)

			if form.is_valid():

				user = form.save(commit=False)
				user.is_staff = True
				user.set_password(request.POST.get('password'))
				user.save()

				if user.role == User.MANAGER:

					group = Group.objects.get(name='Managers')
					group.user_set.add(user)

				messages.info(request, 'The user was added!')

				return redirect('/chat-admin/')
		else:
			form = AddUserForm()
			
		return render(request, 'chat/add_user.html', {'form':form})
	else:
		messages.error(request, 'You dont\'t access to add users!')

		return redirect('/chat-admin/')

chat/templates/chat/add_user.html
{% extends 'core/base.html' %}


{% block content %}
<h1 class="text-2xl mb-6 text-center mt-2"><b>ADD USERS</b></h1>
<br>
<form action="." method="POST">{%csrf_token%}
{{form.as_p}}
<button class="mt-6 inline-block py-2 px-6 bg-blue-600 rounded-xl text-white">Add User</button>
</form><br>


{% endblock %}

chat/templates/chat/admin.html
{% extends 'core/base.html' %}


{% block content %}

<h1 class="txt-2xl">Chat Admin</h1>

{% if perms.user.add_user %}
	<div class="mt-8">
		<h2 class="mb-4 text-lg">Users</h2>

		<a href="{% url 'chat:add_user' %}" class="inline-block py-2 px-6 bg-blue-600 text-white rounded-xl">Add User</a>

		<div class="mt-6">
			{% for user in users %}
			    <div class="grid grid-cols-4 gap-4 py-2 {% cycle 'bg-gray-100' '' %}">
			    	<p class="px-2"><a href="{% url 'chat:user_detail' user.pk %}">{{user.name}}</a></p>
			    	<p class="px-2">{{user.email}}</p>
			    	<p class="px-2">{{user.get_role_display}}</p>
			    	<p class="px-2" class="text-right">
			    		{% if perms.user.edit_user %}
			    			<a href="{% url 'chat:edit_user' user.pk %}" class="underline">Edit</a>
			    		{% endif %}
			    	</p>
			    </div>
			{% endfor %}
		</div>
	</div>
{% endif %}

<hr class="my-6">

<div class="mt-8">
	<h2 class="mb-4 text-lg">Rooms</h2>
	{% include 'chat/partials/room_list.html' %}
</div>

{% endblock %}

chat/templates/chat/edit_user.html
{% extends 'core/base.html' %}


{% block content %}
<h1 class="text-2xl mb-6 text-center mt-2"><b>EDIT USER</b></h1>
<br>
<form action="." method="POST">{%csrf_token%}
{{form.as_p}}
<button class="mt-6 inline-block py-2 px-6 bg-blue-600 rounded-xl text-white">Save Changes</button>
</form><br>


{% endblock %}

chat/templates/chat/room.html
{% extends 'core/base.html' %}


{% load static chatextras %}

{% block content %}

<h1 class="txt-2xl">Room "{{ room.uuid }}"</h1>


<hr class="my-6">

<p class="mb-6">
	<b>Name: </b>{{ room.client }}<br>
	<b>Started: </b>{{ room.created_at|timesince }} ago<br>
	<b>Status: </b>{{ room.get_status_display }}<br>
	<b>Page: </b>{{ room.url }}<br>
	<b>Agent: </b>{% firstof room.agent.name 'None Yet...' %}<br>
</p>

<hr class="my-6">

<div id="chat_message" class="mb-4 p-4 bg-gray-100 rounded-xl h-[300px] overflow-scroll flex flex-col flex-grow">
	{% for message in room.messages.all %}
		<div class="flex w-full max-w-md mt-2 space-x-3 {% if message.created_by %}ml-auto justify-end{% endif %}">
			{% if not message.created_by %}
				<div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-100 text-center pt-2">
					{{ message.sent_by|initials }}
				</div>
			{% endif %}
			<div>
				<div class="p-4 rounded-xl{% if message.created_by %}bg-blue-600 text-white{% else %}bg-gray-300{% endif %}">
					<p class="text-sm">{{ message.body }}</p>
				</div>
				<span class="text-sm text-gray-500 leading-none">{{ message.created_at|timesince }} ago</span>
			</div>
			{% if message.created_by %}
				<div class="flex-shrink-0 h-10 w-10 rounded-full bg-gray-100 text-center pt-2">
					{{ message.sent_by|initials }}
				</div>
			{% endif %}
		</div>
	{% endfor %}
</div>
{% if room.status == 'active' %}
	<input type="text" name="message" id="chat_input" class="w-full mb-4 p-4 bg-gray-100 rounded-xl" placeholder="Type Your Message Here...">
	<button id="chat_submit" class="py-2 px-6 bg-blue-600 text-white rounded-xl">Send</button>
{% endif %}

{% endblock %}

{% block scripts %}
	{% if room.status == 'active' %}
		{{ room.uuid|json_script:'room_uuid'}}
		{{ request.user.name|json_script:'user_name'}}
		{{ request.user.id|json_script:'user_id'}}
		<script src="{% static 'js/main_admin.js' %}"></script>
	{% endif %}
{% endblock %}

chat/templates/chat/user_detail.html
{% extends 'core/base.html' %}


{% block content %}

<h1 class="txt-2xl text-center text-upper"><b>{{user.name}}'S Detail</b></h1>

<hr class="my-6">

<div class="mt-8">
	<h2 class="mb-4 text-lg">Rooms</h2>
	{% include 'chat/partials/room_list.html' %}
</div>

{% endblock %}