chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns =[
	path('api/create_room/<str:uuid>', views.create_room, name="create_room"),
	path('chat-admin/', views.admin, name='admin'),
	path('chat-logout/', views.logout_user, name='logout'),
	path('chat-admin/add-user/', views.add_user, name='add_user'),
	path('chat-admin/users/<uuid:uuid>/', views.user_detail, name='user_detail'),
	path('chat-admin/users/<uuid:uuid>/edit/', views.edit_user, name='edit_user'),
	path('chat-admin/<str:uuid>/', views.room, name='room'),
	path('chat-admin/<str:uuid>/delete/', views.delete_room, name='delete_room'),
]

core/urls.py
from django.urls import path

from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

jatte/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('chat.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="mb-6 text-2xl text-center"><b>SENT CV SUMMARY</b></h1>
{% include 'core/head.html' %}
{% include 'core/body.html' %}
{% endblock %}

core/templates/core/base.html
{% load static %}

<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    </head>

    <body class="">
        <div class="">
            <nav class="p-6 bg-blue-600 text-white flex justify-between items-center">
                <a href="{% url 'core:index' %}" class="text-xl">Aaronicks</a>

                <div class="flex items-center space-x-4">
                    <a href="{% url 'core:index' %}">Home</a>
                    <a href="{% url 'core:about' %}">About</a>

                    {% if request.user.is_authenticated %}
                        <a href="{% url 'chat:admin' %}" class="inline-block py-4 px-6 bg-emerald-800 text-grey-500 rounded-xl">Chat Admin</a>
                        <a href="{% url 'chat:logout' %}" class="inline-block py-4 px-6 bg-rose-800 rounded-xl">Logout</a>
                
                    {% endif %}
                </div>
            </nav>

            <main class="max-w-6xl mx-auto p-6">
                {% if messages %}
                    <div class="message mb-6 p-6 bg-gray-800 text-white rounded-xl">
                        {% for message in messages %}
                            <p class="text-center">{{ message }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                {% block content %}

                {% endblock %}
            </main>
        </div>

        <footer class="py-12 px-6 bg-gray-800 text-white text-center text-xs">
            <p>Copyright (c) 2024 - Solanke Afolabi</p>
        </footer>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

core/templates/core/body.html
<main class="flex gap-x-10">
            <div class="w-2/6 px-2">
                <!-- contact details -->
                <strong class="text-xl font-medium">Details</strong>
                <ul class="mt-2 mb-10">
                    <li class="px-2 mt-2"><strong class="mr-1 underline">Phone </strong>
                        <a href="tel:+821023456789" class="block">+2347-069-952-176</a>
                    </li>
                    <li class="px-2 mt-2"><strong class="mr-1 underline">E-mail </strong>
                        <a href="mailto:" class="block">aaronicks@gmail.com</a>
                    </li>
                    <li class="px-2 mt-2"><strong class="mr-1 underline">Location</strong><span class="block">Lagos,
                            Nigeria</span></li>
                </ul>

                <!-- github stats -->

                <br>
                <!-- skills -->
                <strong class="text-xl font-medium underline text-center">Skills</strong>
                <ul class="mt-2 mb-10">
                    <li class="px-2 mt-1">HTML</li>
                    <li class="px-2 mt-1">CSS</li>
                    <li class="px-2 mt-1">JavaScript</li>
                    <li class="px-2 mt-1">Python</li>
                    <li class="px-2 mt-1">Bootstrap Css</li>
                    <li class="px-2 mt-1">Bootstrap Css</li>
                    <li class="px-2 mt-1">PHP</li>
                    <li class="px-2 mt-1">UI/UX Design</li>
                    <li class="px-2 mt-1">Laravel</li>
                    <li class="px-2 mt-1">Tailwind Css</li><br>



               
                <strong class="text-xl font-medium underline">Hobbies</strong>
                <ul class="mt-2">
                    <li class="px-2 mt-1">Sustainability</li>
                    <li class="px-2 mt-1">New technologies</li>
                    <li class="px-2 mt-1">Blogging on dev.to</li>
                    <li class="px-2 mt-1">Investment</li>
                    <li class="px-2 mt-1">Travel</li>
                </ul>
            </div>
            <!-- info -->
            <div class="w-4/6">
                <section>
                    <!-- about me -->
                    <h2 class="text-2xl pb-1 border-b font-semibold">SUMMARY</h2>
                    <p class="mt-4 text-xs">As an experienced web developer, I have a strong foundation in essential web technologies like HTML, CSS, and JavaScript, and I'm dedicated to leveraging emerging tech for more efficient code, actively pursuing opportunities to contribute to web solutions and ensuring my ongoing growth in the field.
                    </p>

                </section>
                <section>
                    <!-- projects -->
                    <h2 class="text-2xl mt-6 pb-1 border-b font-semibold">Projects</h2>
                    <ul class="mt-1">

                        <li class="py-2">
                            <div class="flex justify-between my-1">
                               <strong>URL Shotener</strong>                       
                            </div>
                            <p class="text-xs">Thhis project was built for developler who would nnot like to cram long urls by heart. </p>
                        </li>

                        <li class="py-2">
                            <div class="flex justify-between my-1">
                                <strong>Django CRM</strong>  
                            </div>
                            <p class="text-xs">Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe
                                expedita illum optio porro suscipit rerum labore veritatis autem eum totam veniam
                                repudiandae repellendus perspiciatis eligendi sequi maiores, cum ipsa ut!
                                Dolorum aliquid quaerat, dolore nemo, vero alias non porro quam totam impedit
                                repellat voluptas, nobis harum quae dolorem accusantium consequatur. Recusandae
                                cupiditate possimus natus consequuntur aliquid, molestias provident saepe nobis.
                            </p>
                        </li>
                        <li class="py-2">
                            <div class="flex justify-between my-1">
                                <strong>SocialBook</strong>
                            </div>
                            <p class="text-xs">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus,
                                odio autem non possimus adipisci, sed sequi culpa ipsa necessitatibus repellat
                                rerum. Obcaecati nobis modi voluptate nam minus praesentium soluta voluptatibus!
                                Minima temporibus deserunt laborum, expedita ad molestiae perferendis? Ipsa aut,
                                necessitatibus expedita rem iure minus sit voluptates magni, sequi eum architecto
                                excepturi tempora dolorum soluta quam odit amet nobis incidunt.</p>
                        </li>
                        <li class="py-2">
                            <div class="flex justify-between my-1">
                                <strong>School Management System</strong>
                            </div>
                            <p class="text-xs">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ducimus
                                suscipit soluta at doloremque ipsa unde, doloribus beatae delectus odio dolorum
                                consequatur libero esse ratione nostrum nihil quaerat alias cupiditate assumenda?
                                Nesciunt unde aliquid quam quisquam excepturi deserunt ipsa doloremque culpa itaque.
                                Esse consectetur odit est laboriosam facilis! Accusamus inventore vel magni sed
                                aliquid! Aspernatur dolores, nam id fugit ad aliquam.
                            </p>
                        </li>
                    </ul>
                </section>
                <section>
                    <!-- work experiences -->
                    <h2 class="text-2xl mt-6 pb-1 border-b font-semibold">Work Experiences</h2>
                    <ul class="mt-2 px-2">
                        <li class="p-2">
                            <p class="flex justify-between text-sm"><strong class="text-base">Plura Transit
                            </strong>2022 - 2023</p>
                            <p class="flex justify-between text-base">Web Apllication Administrator | Team Manager<small>Sango-ota, Ogun State</small></p>
                            <p class="text-justify text-xs">Defined and implemented the web development strategy for the transportationcompany, aligning it with the overall business goals. <br>Created a web based application tools designed to efficiently oversee and enhance the entire supply chain workflow, spanning from raw material sourcing to the delivery of final products to customers. <br>Crafted an application that enabled me to adeptly lead and supervise a team of logistics specialists, setting objectives and ensuring seamless operations by leveraging database expertise. <br>Streamlined daily tasks for both technical and administrative personnel while providing regular reports to my superiors <br> Developed a notification system that proactively alerted us to impending equipment maintenance deadlines, covering vehicles, forklifts, trucks, and storage systems. <br>
                            </p>
                        </li>
                        <li class="pt-2 p-2">
                            <p class="flex justify-between text-sm"><strong class="text-base">Pythronix (Self)
                            </strong>2021 - 2022</p>
                            <p class="flex justify-between text-base">Freelance Web Developer<small>Ibadan , Oyo State</small></p>
                            <p class="text-justify text-xs">Empowered the less privileged in the society through the organization of professional training and classes. <br>Managed multiple large-scale projects, delivering all on time and within budget <br>Developed and maintained the web application for Farmex Meyer Nigeria Limited, Proxy Visas, Babaoja which was an Ecommerce website and also developed new features for them. <br> Enrolled in some self-development training programmes with Google and Coursera. <br>Recommended and Supplied computer hardware and phone accessories to some organizations and individuals. <br>

                            </p>
                        </li>
                    </ul>
                </section>
                <section>
                    <!-- education -->
                    <h2 class="text-2xl mt-6 pb-1 border-b font-semibold">Education</h2>
                    <ul class="mt-2 px-2">
                        <li class="pt-2 p-2">
                            <p class="flex justify-between text-sm"><strong class="text-base">University of Michigan (Coursera)</strong>2021</p>
                            
                        </li>
                        <li class="pt-2">
                            <p class="flex justify-between text-sm"><strong class="text-base">Universtiy of Ibadan</strong>2008-2015</p> <br>
                        </li>
                    </ul>
                    <p class="text-sm text-center"><strong class="text-base text-center">MORE ON MY SENT CURRICULUM VITAE</strong></p> <br>
                </section>
            </div>
        </main>

core/templates/core/head.html
 <div class="border border-gray-300 rounded-sm shadow-lg py-10 px-10 w-4/5 mt-10 mb-10">
        <!-- header (profile) -->
        <header>
            <!-- social icons-->
            <ul class="flex flex-wrap justify-end gap-2">
                <!-- linkedin -->
                <li>
                    <a href="https://www.linkedin.com/"
                        class="bg-blue-600 p-2 font-semibold text-white inline-flex items-center space-x-2 rounded"
                        target=”_blank”>
                        <!-- <svg class="w-5 h-5 fill-current" role="img" viewBox="0 0 256 256"
                            xmlns="http://www.w3.org/2000/svg">
                            <g>
                                <path
                                    d="M218.123122,218.127392 L180.191928,218.127392 L180.191928,158.724263 C180.191928,144.559023 179.939053,126.323993 160.463756,126.323993 C140.707926,126.323993 137.685284,141.757585 137.685284,157.692986 L137.685284,218.123441 L99.7540894,218.123441 L99.7540894,95.9665207 L136.168036,95.9665207 L136.168036,112.660562 L136.677736,112.660562 C144.102746,99.9650027 157.908637,92.3824528 172.605689,92.9280076 C211.050535,92.9280076 218.138927,118.216023 218.138927,151.114151 L218.123122,218.127392 Z M56.9550587,79.2685282 C44.7981969,79.2707099 34.9413443,69.4171797 34.9391618,57.260052 C34.93698,45.1029244 44.7902948,35.2458562 56.9471566,35.2436736 C69.1040185,35.2414916 78.9608713,45.0950217 78.963054,57.2521493 C78.9641017,63.090208 76.6459976,68.6895714 72.5186979,72.8184433 C68.3913982,76.9473153 62.7929898,79.26748 56.9550587,79.2685282 M75.9206558,218.127392 L37.94995,218.127392 L37.94995,95.9665207 L75.9206558,95.9665207 L75.9206558,218.127392 Z M237.033403,0.0182577091 L18.8895249,0.0182577091 C8.57959469,-0.0980923971 0.124827038,8.16056231 -0.001,18.4706066 L-0.001,237.524091 C0.120519052,247.839103 8.57460631,256.105934 18.8895249,255.9977 L237.033403,255.9977 C247.368728,256.125818 255.855922,247.859464 255.999,237.524091 L255.999,18.4548016 C255.851624,8.12438979 247.363742,-0.133792868 237.033403,0.000790807055">
                                </path>
                            </g>
                        </svg> -->
                    </a>
                </li>
                <li>
                    <!-- github -->
                    <a href="https://github.com/"
                        class="bg-gray-700 p-2 font-medium text-white inline-flex items-center space-x-2 rounded"
                        target=”_blank”>
                        <!-- <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                            aria-hidden="true" role="img" class="w-5" preserveAspectRatio="xMidYMid meet"
                            viewBox="0 0 24 24">
                            <g fill="none">
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                    d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385c.6.105.825-.255.825-.57c0-.285-.015-1.23-.015-2.235c-3.015.555-3.795-.735-4.035-1.41c-.135-.345-.72-1.41-1.23-1.695c-.42-.225-1.02-.78-.015-.795c.945-.015 1.62.87 1.845 1.23c1.08 1.815 2.805 1.305 3.495.99c.105-.78.42-1.305.765-1.605c-2.67-.3-5.46-1.335-5.46-5.925c0-1.305.465-2.385 1.23-3.225c-.12-.3-.54-1.53.12-3.18c0 0 1.005-.315 3.3 1.23c.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23c.66 1.65.24 2.88.12 3.18c.765.84 1.23 1.905 1.23 3.225c0 4.605-2.805 5.625-5.475 5.925c.435.375.81 1.095.81 2.22c0 1.605-.015 2.895-.015 3.3c0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z"
                                    fill="currentColor" />
                            </g>
                        </svg> -->
                    </a>
                </li>
            </ul>
            <div class="flex justify-between items-center">
                <div>
                    <div class="bg-cover bg-no-repeat rounded-full h-52 w-52"
                        style="background-image: url(../bootstrap/dog.jpg)">
                    </div>
                </div>
                <div class="grid justify-items-end">
                    <h1 class="text-7xl font-extrabold">SOLANKE AFOLABI H.</h1>
                    <p class="text-xl mt-5">FullStack Developer</p>
                </div>
            </div>
        </header>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

    <div class="mt-12 py-12 px-8 grid grid-cols-5 gap-4 items-center border border-blue-200 rounded-xl">
        <div class="col-span-2">
            <img src="{% static 'images/header.png' %}">
        </div>

        <div class="col-span-3">
            <h1 class="mb-8 text-3xl">Welcome to ChatMe</h1>

            <h2 class="text-lg text-gray-500">This App was developed by me, Solanke Afolabi H. All instruction on its functionality will be in the readme.md. I will be looking forward to your call up</h2>
        </div>
    </div>

    <div class="mt-12 py-12 px-8 grid grid-cols-3 gap-4 items-center">
        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>

        <div class="text-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-12 h-12 mb-8 text-rose-600 mx-auto">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
            </svg>  
            
            <h3 class="mb-4 text-xl text-gray-800">A dummy title</h3>

            <p class="text-gray-500">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan tortor at sem fermentum tempor.</p> 
        </div>
    </div>

    {% include 'chat/partials/chat_bubble.html' %}
    
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}